name: crawl

on:
  workflow_dispatch:
  push:
    branches: ['main']
  schedule:
  - cron: '0 6 * * *' # Daily at 6 AM

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x
    - uses: google-github-actions/setup-gcloud@v0
      with:
        install_components: alpha,beta

    - run: |
        rm -r gcloud/
        ./crawl.sh
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "gcloud: ${timestamp}" || exit 0
        git tag $(gcloud version --format=json | jq -r '."Google Cloud SDK"')
        git push --tags

